export { default as ChatIcon } from "../../public/svg/chat.svg";
export { default as ValutChatBuddyIcon } from "../../public/svg/valut-chat-buddy.svg";
export { default as ContactIcon } from "../../public/svg/contact.svg";
export { default as ExchangeIcon } from "../../public/svg/exchange.svg";
export { default as NetworksIcon } from "../../public/svg/networks.svg";
export { default as SendIcon } from "../../public/svg/send.svg";
export { default as TokenIcon } from "../../public/svg/tokens.svg";
export { default as ArrowGotoIcon } from "../../public/svg/arrow-goto.svg";
export { default as AlertIcon } from "../../public/svg/alert.svg";
export { default as MarketInfoIcon } from "../../public/svg/market-info.svg";
export { default as SendTxnIcon } from "../../public/svg/send-transactions.svg";
export { default as EditContactIcon } from "../../public/svg/edit-contact.svg";
export { default as RemoveContactIcon } from "../../public/svg/remove-contact.svg";
export { default as RoundedCheckIcon } from "../../public/svg/rounded-check.svg";
// export { default as AddContactIcon } from '../../public/svg/add-contact.svg';
export { default as AddNewChatIcon } from "../../public/svg/add-new-chat.svg";
export { default as MoreIcon } from "../../public/svg/more.svg";
